[versions]

minSdk = "26"
targetSdk = "36"
compileSdk = "36"

agp = "8.9.2"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.28"
gradle-secrets = "2.0.1"
kotlinxSerializationJson = "1.7.3"

# Core
coreKtx = "1.17.0"
appcompat = "1.7.0"
material = "1.12.0"

# Test
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

# DI
hilt = "2.56.2"

# Compose
composeBom = "2025.10.01"
activityCompose =  "1.11.0"
lifecycleCompose = "2.7.0"

# Навигация
navCompose = "2.9.5"
hiltNavCompose = "1.3.0"

#Database
room = "2.7.1"

# Network
okhttp = "4.12.0"
retrofit = "2.11.0"


[libraries]
# AndroidX core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# Material
androidx-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-material-iconsCore = { group = "androidx.compose.material", name = "material-icons-core"}
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# Hilt
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# Compose BOM
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

# Compose
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-ui-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# Navigation
jetpack-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navCompose" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavCompose" }

# Room
room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ksp = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }


#Network
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gradle-secrets-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "gradle-secrets" }

[bundles]
compose = [
    "androidx-ui",
    "androidx-ui-runtime",
    "androidx-ui-foundation",
    "androidx-material3",
    "androidx-material-iconsExtended",
    "androidx-material-iconsCore",
]

compose-debug = [
    "androidx-ui-tooling",
    "androidx-ui-test-manifest",
    "androidx-ui-tooling-preview",
]